name: latentde
channels:
  - pytorch
  - huggingface
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - lightning=2.1.2
  - pip=23.3.1
  - python=3.10.13
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - transformers=4.33.3
  - pip:
      - scikit-learn==1.3.2
      - tape-proteins==0.5
      - matplotlib==3.8.2
      - pandas==2.1.4
      - rootutils==1.0.7
      - seaborn==0.13.0
      - wandb==0.16.1
      - tabulate==0.9.0
      - polyleven==0.8